version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: contacthub_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: contacthub
      POSTGRES_PASSWORD: password
      POSTGRES_DB: contacthub_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U contacthub -d contacthub_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
