services:
  - type: web
    name: contacthub-app
    env: node
    buildCommand: npm ci && npx prisma generate && npm run build
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: contacthub-db
          property: connectionString
    healthCheckPath: /health

databases:
  - name: contacthub-db
    plan: free
    ipAllowList: []
